COLLECTION_NAME = u'RPI_DATA'
DOCUMENT_MAIN_DOOR = 'DOC_MAIN_DOOR'
DOCUMENT_LIGHT = 'DOC_TOUCH_LIGHT'
DOCUMENT_WINDOW='DOC_IR_SERVO'
DOCUMENT_TEMP = 'DOC_TEMPERATURE'

DOCUMENT_CAMERA = u'DOC_CAMERA'
STORAGE_FOLDER_CAMERA_IMAGES = u'camera_rolls'
CAMERA_IMAGE_NAME = u'camera_image1.jpg'